openapi: 3.0.0
info:
  version: v2.0
  title: ONEm JSON response schema
  description: ''
paths: {}
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/romeo1m/schemajson/v1
components:
  schemas:
    MenuItem:
      title: MenuItem
      description: An item in a menu. Depending on its type, a menu item can be either
        an option (type=option) or an option separator (type=content)
      type: object
      properties:
        type:
          title: Type
          description: The type of the menu item.
          enum:
          - option
          - content
          type: string
        description:
          title: Description
          description: The displayed text of a menu item.
          type: string
        text_search:
          title: Text_Search
          description: Field to add more context for searching in options
          type: string
        method:
          title: Method
          description: The HTTP method called when the menu item is selected.
          enum:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - HEAD
          - OPTIONS
          - TRACE
          type: string
        path:
          title: Path
          description: The path called when the menu item is selected.
          type: string
      required:
      - type
      - description
    MenuMeta:
      title: MenuMeta
      description: Configuration fields for `Menu`
      type: object
      properties:
        auto_select:
          title: Auto_Select
          description: If the `Menu` has only one option, it is automatically selected,
            without asking the user for selection
          default: false
          type: boolean
    Menu:
      title: Menu
      description: A top level component that permits displaying a navigable menu
        or a plain text.
      type: object
      properties:
        type:
          title: Type
          description: The type of the Menu object is always "menu"
          const: menu
          type: string
        body:
          title: Body
          description: The body/content of the menu
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
        header:
          title: Header
          description: The header of the menu.
          type: string
        footer:
          title: Footer
          description: The header of the menu.
          type: string
        meta:
          title: Meta
          description: Configuration fields for `Menu`
          allOf:
          - $ref: '#/components/schemas/MenuMeta'
      required:
      - body
    MenuItemFormItem:
      title: MenuItemFormItem
      description: An item in a form's menu
      type: object
      properties:
        type:
          title: Type
          description: The type of a menu item inside a form
          enum:
          - option
          - content
          type: string
        description:
          title: Description
          description: The description of this MenuItemFormItem
          type: string
        value:
          title: Value
          description: The value of this MenuItemFormItem, used in form serialization
          type: string
        text_search:
          title: Text_Search
          description: Field to add more context for searching in options
          type: string
      required:
      - type
      - description
    MenuFormItemMeta:
      title: MenuFormItemMeta
      description: Configuration fields for a `FormItem`
      type: object
      properties:
        auto_select:
          title: Auto_Select
          description: Will be automatically selected if set to true and in case of
            a single option in the menu
          default: false
          type: boolean
        multi_select:
          title: Multi_Select
          description: It allows multiple options to be selected
          default: false
          type: boolean
        numbered:
          title: Numbered
          description: Display numbers instead of letter option markers
          default: false
          type: boolean
    FormItem:
      title: FormItem
      description: Component used to ask a user for a certain type of free input
      type: object
      properties:
        type:
          title: Type
          description: The type of data expected from the user
          enum:
          - string
          - date
          - datetime
          - hidden
          - int
          - float
          - form-menu
          - email
          - url
          - location
          type: string
        name:
          title: Name
          description: The name of this FormItem, used in form serialization
          type: string
        description:
          title: Description
          description: The description of this FormItem
          type: string
        header:
          title: Header
          description: If provided will overwrite the Form.header
          type: string
        footer:
          title: Footer
          description: If provided will overwrite the Form.footer
          type: string
        body:
          title: Body
          description: Required only for type=form-menu
          type: array
          items:
            $ref: '#/components/schemas/MenuItemFormItem'
        value:
          title: Value
          description: Required for type=hidden
          type: string
        chunking_footer:
          title: Chunking_Footer
          description: Shown in the footer of the sms chunks
          type: string
        confirmation_label:
          title: Confirmation_Label
          description: Shown in the confirmation menu
          type: string
        min_length:
          title: Min_Length
          description: Validates the user input - for type=string
          type: integer
        min_length_error:
          title: Min_Length_Error
          description: Message to be shown on min_length error
          type: string
        max_length:
          title: Max_Length
          description: Validates the user input - for type=string
          type: integer
        max_length_error:
          title: Max_Length_Error
          description: Message to be shown on max_length error
          type: string
        min_value:
          title: Min_Value
          description: Validates the user input - for type=int|float
          type: number
        min_value_error:
          title: Min_Value_Error
          description: Message to be shown on min_value error
          type: string
        max_value:
          title: Max_Value
          description: Validates the user input - for type=int|float
          type: number
        max_value_error:
          title: Max_Value_Error
          description: Message to be shown on max_value error
          type: string
        meta:
          title: Meta
          description: Applies only for type=form-menu
          allOf:
          - $ref: '#/components/schemas/MenuFormItemMeta'
        method:
          title: Method
          description: http method, how the callback url should be triggered
          enum:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - HEAD
          - OPTIONS
          - TRACE
          type: string
        required:
          title: Required
          description: Can be skipped if set to false
          default: false
          type: boolean
        status_exclude:
          title: Status_Exclude
          description: If true this step will be excluded from the form completion
            status
          default: false
          type: boolean
        status_prepend:
          title: Status_Prepend
          description: If true this step will be prepended to the body pre of the
            response - appended otherwise
          default: false
          type: boolean
        url:
          title: Url
          description: Callback url triggered right after the choice has been set
            for this form item
          type: string
        validate_type_error:
          title: Validate_Type_Error
          description: An error message to be shown on basic type validation
          type: string
        validate_type_error_footer:
          title: Validate_Type_Error_Footer
          description: Shown in the error message footer
          type: string
        validate_url:
          title: Validate_Url
          description: 'the callback url path (GET) triggered to validate user input
            with query string ?name=user_input - url must return json content {"valid":
            True/False, "error": "Some validation error message"}'
          type: string
      required:
      - type
      - name
    FormMeta:
      title: FormMeta
      description: Configuration fields for a Form
      type: object
      properties:
        completion_status_show:
          title: Show completion status
          description: Whether to display the completions status
          default: false
          type: boolean
        completion_status_in_header:
          title: Show completion status in header
          description: Whether to display the completion status in header
          default: false
          type: boolean
        confirmation_needed:
          title: Confirmation needed
          description: Whether to add an additional item at the end of the form for
            confirmation
          default: false
          type: boolean
    Form:
      title: Form
      description: A top level component used to acquire information from user
      type: object
      properties:
        type:
          title: Type
          description: The type of a form is always form
          const: form
          type: string
        body:
          title: Body
          description: Sequence of components used to acquire the pieces of data needed
            from user
          type: array
          items:
            $ref: '#/components/schemas/FormItem'
        method:
          title: Method
          description: The HTTP method used to send the form data
          default: POST
          enum:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - HEAD
          - OPTIONS
          - TRACE
          type: string
        path:
          title: Path
          description: The path used to send the form data
          type: string
        header:
          title: Header
          description: The header of the form. It can be overwritten by each body
            component
          type: string
        footer:
          title: Footer
          description: The footer of the form. It can be overwritten by each body
            component
          type: string
        meta:
          title: Meta
          description: Contains configuration flags
          allOf:
          - $ref: '#/components/schemas/FormMeta'
      required:
      - body
      - path
    Response:
      title: Response
      description: A JSON-serialized instance of Response must be sent as response
        to the ONEm platform. It can be built only from a top level object (Menu,
        Form).
      type: object
      properties:
        content_type:
          title: Content type
          description: The type of the content of the response
          enum:
          - form
          - menu
          type: string
        content:
          title: Content
          description: The content of the response
          anyOf:
          - allOf:
            - $ref: '#/components/schemas/Form'
          - allOf:
            - $ref: '#/components/schemas/Menu'
      required:
      - content_type
      - content
